### ISSUE TITLE
Should this work with a Web AppBuilder app hosted on AGOL?

### ISSUE THREAD

**Issue by kenm09** [Esri/map-gallery-template-js#11]
Clicking the thumbmail of a Web AppBuilder app throws error 404. All other apps and web maps work fine. It is only a Web AppBuilder application that has this issue.

I just get HTTP Error 404.0 - Not Found

Here is my workflow. I created a Web Mapping Application using the web appbuilder on AGOL and shared it with my group. I can see the web appviewer in my template, but when I click on it, the resource can't be found. But if a web map is selected instead, it works just fine.

**Comment by driskull** [comment]
This is going to be addressed by Web App Builder.
