### ISSUE TITLE
filter type only work for one type

### ISSUE THREAD

**Issue by chen7012** [Esri/map-gallery-template-js#13]
in the option.js file, there is a parameter called "filterType", but could only take one type at a time, what if, for example, wants to filter web maps and application.

**Comment by driskull** [comment]
hey @chen7012 

You could set a "customFilter" property in the options file to set a custom filter query. See the code below on how that might look.

Or you could define another filter type here:
https://github.com/Esri/map-gallery-template-js/blob/master/javascript/home.js#L726
