### ISSUE TITLE
Proxy Help

### ISSUE THREAD

**Issue by wspiking** [Esri/map-gallery-template-js#14]
Hi @driskull I believe you helped with me out with a proxy question on the pim template.  I'm now testing my proxy with the map gallery and running into problems.  Any suggestions would be much appreciated.

Here's what I've done so far.

1. updated the option.js with the group id, proxy url, and sharing url.
2. updated the common.js with my proxy url on line 286.  I think I'm missing something else between lines 261 and 288, but I'm not exactly sure.

     //Check to see if the app is hosted or a portal. In those cases set the sharing url and the proxy.                Otherwise use
        //the sharing url set it to arcgis.com. We know app is hosted (or portal) if it has /apps/ in the url 
        //templates can be at /apps or /home/webmap/templates
        var appLocation = location.pathname.indexOf("/apps/");
        if (appLocation === -1) {
          appLocation = location.pathname.indexOf("/home/");
        }
        this._options.isOrg = false;
        if (this._options.sharingurl) { //sharing url specified 
          this._options.mobilePortalUrl = 'arcgis:' + '//' + location.host;
          //sharing url set in config file so use default services 
        } else if (appLocation !== -1) { //hosted or portal 
          this._options.isOrg = true;
          var instance = location.pathname.substr(0, appLocation);
          this._options.sharingurl = location.protocol + "//" + location.host + instance;
          this._options.proxyurl = location.protocol + '//' + location.host + instance + "/sharing/proxy";
          this._options.mobilePortalUrl = 'arcgis:' + '//' + location.host;
        } else { //default to arcgis.com 
          this._options.sharingurl = location.protocol + "//" + "www.arcgis.com";
          this._options.mobilePortalUrl = "arcgis://www.arcgis.com";
        }
        arcgisUtils.arcgisUrl = this._options.sharingurl + "/sharing/rest/content/items";
        this._options.portalurl = this._options.sharingurl;
        //Set the proxy. If the app is hosted use the default proxy. 
        if (this._options.proxyurl) {
          config.defaults.io.proxyUrl = "http://my.url.com/DotNet/proxy.ashx"
          config.defaults.io.alwaysUseProxy = false;
        }

**Comment by driskull** [comment]
hey @wspiking. you shouldn't have to add your proxy in the common.js file. Just adding it here should be enough: https://github.com/Esri/map-gallery-template-js/blob/master/config/options.js#L56

If you need the proxy to automatically work for specific URLs, then you need to add a proxy rule.

https://developers.arcgis.com/javascript/jsapi/esri.urlutils-amd.html#addproxyrule

The rule will say to use the URL to the proxy when it encounters a specific URL.

```javascript
urlUtils.addProxyRule({
  urlPrefix: "route.arcgis.com",
  proxyUrl: "<url_to_proxy>"
});
```

**Comment by wspiking** [comment]
Thank you @driskull.  It looks like I'll need to use the addProxyRule again.  Do you happen to have snippet of code that shows how to call the addProxyRule in your index.html.?  In the PIM template I added it to the js/template.js and it worked great, but I'm having troubles adding it to this template.  Thanks again.

**Comment by wspiking** [comment]
Ok @driskull....i think the reference to my proxy is now working in my index.html, but now I'm receiving the following error.

esri.config.defaults.io.proxyUrl is not set. If making a request to a CORS enabled server, please push the domain into esri.config.defaults.io.corsEnabledServers.

Look familiar?  I see there's a lot of discussion on GeoNet about the error, but I haven't found a solution yet.

**Comment by driskull** [comment]
Hey @wspiking ,

Here's how I would add it:

```javascript
require([
            "config/templateConfig",
            "application/template",
            "application/main",
            "esri/urlUtils"
        ], function(
            templateOptions,
            Template,
            Main,
            urlUtils
        ){
            // create the template. This will take care of all the logic required for template applications 
            var myTemplate = new Template(templateOptions);
            // create my main application. Start placing your logic in the main.js file.
            var myApp = new Main();
            // start template
            myTemplate.startup().then(function(config) {
                urlUtils.addProxyRule({
                  urlPrefix: "route.arcgis.com",
                  proxyUrl: config.proxyUrl
                });
                // The config object contains the following properties: helper services, (optionally) 
                // i18n, appid, webmap and any custom values defined by the application. 
                // In this example we have one called theme. 
                myApp.startup(config);
            }, function(error) {
                // something went wrong. Let's report it.
                myApp.reportError(error);
            });
        });
```

**Comment by wspiking** [comment]
Thank you @driskull. I'll give it a try tomorrow.  I need to take break from the proxy.....for me this is the most frustrating part of deploying these apps.  I was looking at giving the maps and apps template a try and I'm already finding possible probs with the proxy (https://github.com/Esri/map-and-app-gallery-template/issues/163).  You all do a great job with the ui for building the apps, but unless you're deploying on AGO it can be painful for non-developer like myself.  Thank you again for taking the time to reply.
