### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by geospatialem** [Esri/map-gallery-template-js#15]
Hello,

We are trying to re-deploy a local version of the app, however we are running into cache issues when we make changes to JavaScript files, in particular the:
* `css/common.css`
* `javascript/common.js`  
* `nls/template.js`  

Has anyone else encountered this issue and/or know of a way that we can apply a method to refresh the content? We are unable to locate where the common.js and template.js are called into the page. Are the scripts being done so through the Esri JS?

**Comment by driskull** [comment]
Hey @geospatialem!

You can probably put some sort of random datetime string in the request to break the cache when you want to.

Like this:

```
<link href="css/common.css?version=1.0" rel="stylesheet" type="text/css" />
```

You can also use dojo's cacheBust to make all module loads not be cached.

https://dojotoolkit.org/documentation/tutorials/1.10/dojo_config/

or put the param in the module require

```
"application/common?version=1.0",
```

https://github.com/Esri/map-gallery-template-js/blob/master/javascript/home.js#L12
https://github.com/Esri/map-gallery-template-js/blob/master/javascript/map.js#L14


-Matt

**Comment by geospatialem** [comment]
@driskull Thank you for the references to common.js in the `javascript/home.js` and `javascript/map.js` files! 

We were doing a search for "common.js" and were coming up empty (since searching "common" was giving us way more than we bargained for). 

And thanks for the dojo reference and documentation to `cacheBust`, that is **super** handy!!

Do you think it be worthwhile to add in some context to the README.md for others trying to see how the common.js file is dynamically added in, or do you think that's overkill? I can put together a PR if you and your colleagues see an added benefit.

Thanks for getting back to us so quickly!!

**Comment by driskull** [comment]
Sure, that would be helpful 👍
